MCU = STM32F401
BOARD = GENERIC_STM32_F401XC
# PRODUCE_401_LIB_IND = Y

include $(TOP_DIR)/keyboards/pivot/p401/rules.mk
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
curr_kb = qf_chibios_d5_f4
LTO_ENABLE = no
NKRO_ENABLE = no
LTO_ENABLE = no